name: CI Pipeline - PartsUnlimited

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:

  placeholder:
    runs-on: windows-latest
    steps:
      - name: Trigger OK
        run: echo "Pipeline démarré"

  build_and_test:
    runs-on: windows-latest
    steps:

      - name: Étape 1.1 - Checkout du dépôt
        uses: actions/checkout@v3

      - name: Étape 1.2 - Installer .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Étape 1.3 - Restore
        run: dotnet restore PartsUnlimited.sln

      - name: Étape 1.4 - Build
        run: dotnet build PartsUnlimited.sln --configuration Release

      - name: Étape 2.1 - Tests
        run: dotnet test PartsUnlimited.sln --configuration Release --no-build


  build_docker:
    needs: build_and_test
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd PartsUnlimited-aspnet45
          docker build -t ${{ secrets.DOCKER_USERNAME }}/partsunlimited:latest .

      - name: Push Docker image
        run: |
          cd PartsUnlimited-aspnet45
          docker push ${{ secrets.DOCKER_USERNAME }}/partsunlimited:latest
