name: CI Pipeline ASP.NET 4.5

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build solution
        run: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" PartsUnlimited-aspnet45\PartsUnlimited.sln /p:Configuration=Release'

      - name: Run Unit Tests
        run: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\Extensions\TestPlatform\VSTest.Console.exe" PartsUnlimited-aspnet45\test\PartsUnlimited.UnitTests\PartsUnlimited.UnitTests.csproj'
